default_language_version:
  python: python3

exclude: ^(build|dist|tests/samples|\.json)/$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: double-quote-string-fixer
        verbose: true
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: debug-statements
      - id: fix-byte-order-marker
#      - id: fix-encoding-pragma
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]
      - id: detect-private-key
#      - id: detect-aws-credentials
      - id: forbid-submodules
      - id: check-merge-conflict
#      - id: no-commit-to-branch
#        args: [ --branch, staging, --branch, test, --branch, main ]

  - repo: https://github.com/PyCQA/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        args: [ '--max-line-length=120', '--exclude=tests/*' ]

#  - repo: https://github.com/psf/black-pre-commit-mirror
#    rev: 24.8.0
#    hooks:
#      - id: black

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'
    hooks:
      - id: autopep8
        args: [ '--diff', '--max-line-length=120' ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: '6.1.1'
    hooks:
      - id: pydocstyle
        name: "pydocstyle: all but tests"
        args: [ '--match=(?!tests/).*', '--add-ignore=D100,D101,D104,D105,D106,D107,D415', '--convention=google' ]
        additional_dependencies:
          - toml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

#  - repo: https://github.com/asottile/pyupgrade
#    rev: v3.17.0
#    hooks:
#      - id: pyupgrade

#  - repo: https://github.com/asottile/dead
#    rev: v1.5.2
#    hooks:
#      - id: dead

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest-unit
        language: system
        entry: >
          bash -c 'env PYTHONPATH=$VIRTUAL_ENV/lib/python$(cat .python-version)/site-packages:src
          python3 -m pytest tests/unit --cov=app --cov-branch --cov-report term-missing'
        types: [ python ]
        pass_filenames: false
        always_run: true
        stages: [ commit ]
